[package]
name = "train"
type = "contract"
authors = [""]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.81.0", directory="noir-projects/aztec-nr/aztec" }
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.81.0", directory="noir-projects/noir-contracts/contracts/token_contract" }

address_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.81.0", directory="noir-projects/aztec-nr/address-note" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.81.0", directory="noir-projects/aztec-nr/value-note" }
