[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_htlc = "46QyQV1oDcu3CuRgwkrKSBGomScJ2J4UFNjbyRX9MVai"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
