name: Starknet Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  run-starknet-tests:
    name: Run Starknet Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: chains/starknet/tests 
        run: |
          rm -f package-lock.json
          npm install
          npm install typescript ts-node @types/node starknet

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Katana (Foundry) 
        run: |
          # Install Foundry (downloads foundryup and writes it to ~/.foundry/bin)
          curl -L https://foundry.paradigm.xyz | bash
          # load the PATH export that the installer added to ~/.bashrc
          source $HOME/.bashrc
          # install the toolchain
          foundryup
          # show versions for debugging
          which foundryup
          foundryup --version
          which katana || true
        shell: bash -l {0} 

      - name: Start Katana (Local Starknet Devnet)
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          katana --accounts 0 --disable-fee --host 127.0.0.1 --port 5050 > katana.log 2>&1 &
          sleep 10
          echo "=== Katana Logs ==="
          head -40 katana.log
        shell: bash -l {0} 

      - name: Compile Starknet Contracts
        working-directory: chains/starknet/tests
        run: |
          npm run build

      - name: Run Starknet Tests
        working-directory: chains/starknet/tests
        env:
          STARKNET_RPC: http://127.0.0.1:5050
        run: |
          npx ts-node starknet_tests.ts