name: Starknet Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  run-starknet-tests:
    name: Run Starknet Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: chains/starknet/tests 
        run: |
          rm -f package-lock.json
          npm install
          npm install typescript ts-node @types/node starknet

      - name: Install and Run Katana (Local Starknet Devnet)
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$HOME/.foundry/bin:$PATH"
          foundryup
          katana --version
          katana --accounts 3 --disable-fee > /dev/null 2>&1 &
          sleep 5  # Wait for Katana to fully start
        shell: bash -l {0}

      - name: Compile Starknet Contracts
        working-directory: chains/starknet/tests
        run: |
          npm run build # Adjust this command if you use a custom compile command

      - name: Run Starknet Tests
        working-directory: chains/starknet/tests
        run: |
          npx ts-node tests/starknet_tests.ts