name: Starknet Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  run-starknet-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: NPM deps for tests
      working-directory: chains/starknet/tests
      run: |
        rm -f package-lock.json
        npm ci
        npm install typescript ts-node @types/node starknet

    # -- Katana -----------------------------------------------------------------
    - name: Install Katana v1.5.0
      run: |
        set -euo pipefail
        KATANA_VER="v1.5.0"
        curl -L \
          -o katana \
          "https://github.com/dojoengine/dojo/releases/download/${KATANA_VER}/katana-x86_64-unknown-linux-gnu"
        chmod +x katana
        sudo mv katana /usr/local/bin/
        katana --version

    - name: Start Katana devnet
      shell: bash -l {0}
      run: |
        katana --accounts 0 --disable-fee --host 127.0.0.1 --port 5050 > katana.log 2>&1 &
        sleep 10
        head -40 katana.log

    # --------------------------------------------------------------------------
    - name: Compile Starknet contracts
      working-directory: chains/starknet/tests
      run: npm run build

    - name: Run Starknet tests
      working-directory: chains/starknet/tests
      env:
        STARKNET_RPC: http://127.0.0.1:5050
      run: npx ts-node starknet_tests.ts